### ISSUE TITLE
linking fails with latest release 2.1.128

### ISSUE THREAD

**Issue by choppsv1** [CESNET/libyang#2121]
```
libtool: link: gcc -fms-extensions -fno-omit-frame-pointer -funwind-tables -Wall -Wextra -Wformat-nonliteral -Wformat-security -Wswitch-enum -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wpointer-arith -Wbad-function-cast -Wwrite-strings -Wundef -Wimplicit-fallthrough -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -I/usr/local/include -I/usr/include/x86_64-linux-gnu -Werror -O0 -g -g -o isisd/.libs/isisd isisd/isis_bpf.o isisd/isis_dlpi.o isisd/isis_main.o isisd/isis_pfpacket.o yang/frr-isisd.yang.o -Wl,--export-dynamic  isisd/libisis.a lib/.libs/libfrr.so -lcap -ljson-c -lrt
/usr/bin/ld: isisd/libisis.a(isis_nb_config.o): undefined reference to symbol 'lyd_parent'
/usr/bin/ld: /usr/local/lib/libyang.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Compiles fine with 2.1.80

**Comment by choppsv1** [comment]
This was due to `isisd` only using a couple static inline "getter" functions directly, some of those "getter" functions changed to non-inlines so needed to link `isisd` direclty against libyang.
