### ISSUE TITLE
Compilation failure on OS X 10.10.5 (darwin 14.5.0)

### ISSUE THREAD

**Issue by andaru** [CESNET/libyang#443]
Problem: libyang doesn't build on an OS X 10.10.5 systems (perhaps all versions 10.10 or less, judging by similar bugs in other repositories).

```
$ make 
Scanning dependencies of target yangobj
[  2%] Building C object CMakeFiles/yangobj.dir/src/common.c.o
[  5%] Building C object CMakeFiles/yangobj.dir/src/context.c.o
[  8%] Building C object CMakeFiles/yangobj.dir/src/log.c.o
[ 10%] Building C object CMakeFiles/yangobj.dir/src/dict.c.o
[ 13%] Building C object CMakeFiles/yangobj.dir/src/resolve.c.o
[ 16%] Building C object CMakeFiles/yangobj.dir/src/validation.c.o
[ 18%] Building C object CMakeFiles/yangobj.dir/src/xml.c.o
[ 21%] Building C object CMakeFiles/yangobj.dir/src/parser.c.o
/Users/me/go/src/github.com/CESNET/libyang/src/parser.c:288:74: error: use of undeclared identifier 'MAP_ANONYMOUS'
        addr = mmap(NULL, *length, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
                                                                         ^
1 error generated.
make[2]: *** [CMakeFiles/yangobj.dir/src/parser.c.o] Error 1
make[1]: *** [CMakeFiles/yangobj.dir/all] Error 2
make: *** [all] Error 2
```

Darwin's POSIX headers only define `MAP_ANON`, hence adding this to `src/parser.c` corrects the issue for me.

```
#ifdef __APPLE__
#define MAP_ANONYMOUS MAP_ANON
#endif
```
